[workspace]
name = "sub2api"
channels = ["conda-forge"]
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
nodejs = "24.*"
go = "1.25.*"
pnpm = "10.30.*"
podman-compose = ">=1.5.0,<2"
gcc = ">=15.2.0,<15.3"
