[workspace]
name = "sub2api"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[dependencies]
nodejs = "24.*"
go = "1.25.*"
pnpm = "10.30.*"
gcc = ">=15.2.0,<15.3"
lefthook = ">=2.1.1,<3"
golangci-lint = ">=1.62.2,<2"
